import type { Metadata } from 'next'
import { Dancing_Script } from 'next/font/google'
import { GlobalApplication } from './App'
import { Layout } from './layout/Layout'
import { getServerSession } from 'next-auth'
import { authOptions } from '_authOptions/auth/[...nextauth]/route'

const dancing = Dancing_Script({
  variable: '--font-dancing-script',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)

  // Check if session is undefined
  if (!session) {
    return (
      <html className={`${dancing.variable}`} suppressHydrationWarning>
        <body>
          <GlobalApplication session={session}>{children}</GlobalApplication>
        </body>
      </html>
    )
  }

  return (
    <html className={`${dancing.variable}`} suppressHydrationWarning>
      <body>
        <GlobalApplication session={session}>
          <Layout session={session}>{children}</Layout>
        </GlobalApplication>
      </body>
    </html>
  )
}
