export const USERS_KEY_IN_STORE = "users";

export const USER_INFO_REQUEST = `${USERS_KEY_IN_STORE}/USER_INFO_REQUEST`;
export const USER_INFO_REQUEST_SUCCESS = `${USERS_KEY_IN_STORE}/USER_INFO_REQUEST_SUCCESS`;
export const USER_INFO_REQUEST_FAILED = `${USERS_KEY_IN_STORE}/USER_INFO_REQUEST_FAILED`;

export const UPDATE_USER_REQUEST = `${USERS_KEY_IN_STORE}/UPDATE_USER_REQUEST`;
export const UPDATE_USER_REQUEST_SUCCESS = `${USERS_KEY_IN_STORE}/UPDATE_USER_REQUEST_SUCCESS`;
export const UPDATE_USER_REQUEST_FAILED = `${USERS_KEY_IN_STORE}/UPDATE_USER_REQUEST_FAILED`;

export const CLEAR_USER_STORE = `${USERS_KEY_IN_STORE}/CLEAR_USER_STORE`;
