export const USERS_KEY_IN_STORE = "users";

export const USER_INFO_REQUEST = `${USERS_KEY_IN_STORE}/USER_INFO_REQUEST`;
export const USER_INFO_REQUEST_SUCCESS = `${USERS_KEY_IN_STORE}/USER_INFO_REQUEST_SUCCESS`;
export const USER_INFO_REQUEST_FAILED = `${USERS_KEY_IN_STORE}/USER_INFO_REQUEST_FAILED`;

export const UPDATE_USER_REQUEST = `${USERS_KEY_IN_STORE}/UPDATE_USER_REQUEST`;
export const UPDATE_USER_REQUEST_SUCCESS = `${USERS_KEY_IN_STORE}/UPDATE_USER_REQUEST_SUCCESS`;
export const UPDATE_USER_REQUEST_FAILED = `${USERS_KEY_IN_STORE}/UPDATE_USER_REQUEST_FAILED`;

export const NEW_SHIPPING_ADDRESS_REQUEST = `${USERS_KEY_IN_STORE}/NEW_SHIPPING_ADDRESS_REQUEST`;
export const NEW_SHIPPING_ADDRESS_REQUEST_SUCCESS = `${USERS_KEY_IN_STORE}/NEW_SHIPPING_ADDRESS_REQUEST_SUCCESS`;
export const NEW_SHIPPING_ADDRESS_REQUEST_FAILED = `${USERS_KEY_IN_STORE}/NEW_SHIPPING_ADDRESS_REQUEST_FAILED`;

export const EDIT_SHIPPING_ADDRESS_REQUEST = `${USERS_KEY_IN_STORE}/EDIT_SHIPPING_ADDRESS_REQUEST`;
export const EDIT_SHIPPING_ADDRESS_REQUEST_SUCCESS = `${USERS_KEY_IN_STORE}/EDIT_SHIPPING_ADDRESS_REQUEST_SUCCESS`;
export const EDIT_SHIPPING_ADDRESS_REQUEST_FAILED = `${USERS_KEY_IN_STORE}/EDIT_SHIPPING_ADDRESS_REQUEST_FAILED`;

export const DELETE_SHIPPING_ADDRESS_REQUEST = `${USERS_KEY_IN_STORE}/DELETE_SHIPPING_ADDRESS_REQUEST`;
export const DELETE_SHIPPING_ADDRESS_REQUEST_SUCCESS = `${USERS_KEY_IN_STORE}/DELETE_SHIPPING_ADDRESS_REQUEST_SUCCESS`;
export const DELETE_SHIPPING_ADDRESS_REQUEST_FAILED = `${USERS_KEY_IN_STORE}/DELETE_SHIPPING_ADDRESS_REQUEST_FAILED`;

export const CLEAR_USER_STORE = `${USERS_KEY_IN_STORE}/CLEAR_USER_STORE`;
