export const PRODUCT_KEY_IN_STORE = "products";

export const GET_PRODUCTS = `${PRODUCT_KEY_IN_STORE}/GET_PRODUCTS`;
export const GET_PRODUCTS_SUCCESS = `${PRODUCT_KEY_IN_STORE}/GET_PRODUCTS_SUCCESS`;
export const GET_PRODUCTS_FAILED = `${PRODUCT_KEY_IN_STORE}/GET_PRODUCTS_FAILED`;

export const CREATE_PRODUCT = `${PRODUCT_KEY_IN_STORE}/CREATE_PRODUCT`;
export const CREATE_PRODUCT_SUCCESS = `${PRODUCT_KEY_IN_STORE}/CREATE_PRODUCT_SUCCESS`;
export const CREATE_PRODUCT_FAILED = `${PRODUCT_KEY_IN_STORE}/CREATE_PRODUCT_FAILED`;

export const UPDATE_PRODUCT = `${PRODUCT_KEY_IN_STORE}/UPDATE_PRODUCT`;
export const UPDATE_PRODUCT_SUCCESS = `${PRODUCT_KEY_IN_STORE}/UPDATE_PRODUCT_SUCCESS`;
export const UPDATE_PRODUCT_FAILED = `${PRODUCT_KEY_IN_STORE}/UPDATE_PRODUCT_FAILED`;

export const DELETE_PRODUCT = `${PRODUCT_KEY_IN_STORE}/DELETE_PRODUCT`;
export const DELETE_PRODUCT_SUCCESS = `${PRODUCT_KEY_IN_STORE}/DELETE_PRODUCT_SUCCESS`;
export const DELETE_PRODUCT_FAILED = `${PRODUCT_KEY_IN_STORE}/DELETE_PRODUCT_FAILED`;

export const CLEAR_PRODUCTS_KEYS = `${PRODUCT_KEY_IN_STORE}/CLEAR_PRODUCTS_KEYS`;
