export const PRODUCT_KEY_IN_STORE = "products";

export const GET_PRODUCTS = `${PRODUCT_KEY_IN_STORE}/GET_PRODUCTS`;
export const GET_PRODUCTS_SUCCESS = `${PRODUCT_KEY_IN_STORE}/GET_PRODUCTS_SUCCESS`;
export const GET_PRODUCTS_FAILED = `${PRODUCT_KEY_IN_STORE}/GET_PRODUCTS_FAILED`;

export const GET_CATEGORIES_LIST = `${PRODUCT_KEY_IN_STORE}/GET_CATEGORIES_LIST`;
export const GET_CATEGORIES_LIST_SUCCESS = `${PRODUCT_KEY_IN_STORE}/GET_CATEGORIES_LIST_SUCCESS`;
export const GET_CATEGORIES_LIST_FAILED = `${PRODUCT_KEY_IN_STORE}/GET_CATEGORIES_LIST_FAILED`;

export const CREATE_PRODUCT = `${PRODUCT_KEY_IN_STORE}/CREATE_PRODUCT`;
export const CREATE_PRODUCT_SUCCESS = `${PRODUCT_KEY_IN_STORE}/CREATE_PRODUCT_SUCCESS`;
export const CREATE_PRODUCT_FAILED = `${PRODUCT_KEY_IN_STORE}/CREATE_PRODUCT_FAILED`;

export const UPDATE_PRODUCT = `${PRODUCT_KEY_IN_STORE}/UPDATE_PRODUCT`;
export const UPDATE_PRODUCT_SUCCESS = `${PRODUCT_KEY_IN_STORE}/UPDATE_PRODUCT_SUCCESS`;
export const UPDATE_PRODUCT_FAILED = `${PRODUCT_KEY_IN_STORE}/UPDATE_PRODUCT_FAILED`;

export const DELETE_PRODUCT = `${PRODUCT_KEY_IN_STORE}/DELETE_PRODUCT`;
export const DELETE_PRODUCT_SUCCESS = `${PRODUCT_KEY_IN_STORE}/DELETE_PRODUCT_SUCCESS`;
export const DELETE_PRODUCT_FAILED = `${PRODUCT_KEY_IN_STORE}/DELETE_PRODUCT_FAILED`;

export const SOFT_DELETE_PRODUCT = `${PRODUCT_KEY_IN_STORE}/SOFT_DELETE_PRODUCT`;
export const SOFT_DELETE_PRODUCT_SUCCESS = `${PRODUCT_KEY_IN_STORE}/SOFT_DELETE_PRODUCT_SUCCESS`;
export const SOFT_DELETE_PRODUCT_FAILED = `${PRODUCT_KEY_IN_STORE}/SOFT_DELETE_PRODUCT_FAILED`;

export const RESTORE_PRODUCT = `${PRODUCT_KEY_IN_STORE}/RESTORE_PRODUCT`;
export const RESTORE_PRODUCT_SUCCESS = `${PRODUCT_KEY_IN_STORE}/RESTORE_PRODUCT_SUCCESS`;
export const RESTORE_PRODUCT_FAILED = `${PRODUCT_KEY_IN_STORE}/RESTORE_PRODUCT_FAILED`;

export const TRASH_PRODUCT_LIST = `${PRODUCT_KEY_IN_STORE}/TRASH_PRODUCT_LIST`;
export const TRASH_PRODUCT_LIST_SUCCESS = `${PRODUCT_KEY_IN_STORE}/TRASH_PRODUCT_LIST_SUCCESS`;
export const TRASH_PRODUCT_LIST_FAILED = `${PRODUCT_KEY_IN_STORE}/TRASH_PRODUCT_LIST_FAILED`;

export const CLEAR_PRODUCTS_KEYS = `${PRODUCT_KEY_IN_STORE}/CLEAR_PRODUCTS_KEYS`;
