export const ORDERS_KEY_IN_STORE = 'orders';

export const USERS_ORDERS_LIST = `${ORDERS_KEY_IN_STORE}/USERS_ORDERS_LIST`;
export const USERS_ORDERS_LIST_SUCCESS = `${ORDERS_KEY_IN_STORE}/USERS_ORDERS_LIST_SUCCESS`;
export const USERS_ORDERS_LIST_FAILED = `${ORDERS_KEY_IN_STORE}/USERS_ORDERS_LIST_FAILED`;

export const CREATE_ORDERS = `${ORDERS_KEY_IN_STORE}/CREATE_ORDERS`;
export const CREATE_ORDERS_SUCCESS = `${ORDERS_KEY_IN_STORE}/CREATE_ORDERS_SUCCESS`;
export const CREATE_ORDERS_FAILED = `${ORDERS_KEY_IN_STORE}/CREATE_ORDERS_FAILED`;

export const STORE_ORDERS_LIST = `${ORDERS_KEY_IN_STORE}/STORE_ORDERS_LIST`;
export const STORE_ORDERS_LIST_SUCCESS = `${ORDERS_KEY_IN_STORE}/STORE_ORDERS_LIST_SUCCESS`;
export const STORE_ORDERS_LIST_FAILED = `${ORDERS_KEY_IN_STORE}/STORE_ORDERS_LIST_FAILED`;

export const UPDATE_ORDER_BY_VENDOR = `${ORDERS_KEY_IN_STORE}/UPDATE_ORDER_BY_VENDOR`;
export const UPDATE_ORDER_BY_VENDOR_SUCCESS = `${ORDERS_KEY_IN_STORE}/UPDATE_ORDER_BY_VENDOR_SUCCESS`;
export const UPDATE_ORDER_BY_VENDOR_FAILED = `${ORDERS_KEY_IN_STORE}/UPDATE_ORDER_BY_VENDOR_FAILED`;

export const CLEAR_ORDERS_LIST = `${ORDERS_KEY_IN_STORE}/CLEAR_ORDERS_LIST`;
export const CLEAR_ORDERS_ACTIONS_KEYS = `${ORDERS_KEY_IN_STORE}/CLEAR_SOME_KEYS`;
