export const ALL_PUBLIC_PRODUCTS = 'ALL_PUBLIC_PRODUCTS'
export const PRIVATE_PRODUCTS = 'PRIVATE_PRODUCTS'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const GET_CATEGORIES = 'GET_CATEGORIES'
