export const USERS_ORDERS_LIST = `USERS_ORDERS_LIST`
export const CREATE_ORDER = `CREATE_ORDER`
export const STORE_ORDER_LIST = 'STORE_ORDER_LIST'
export const ORDERS_DETAILS_STORE = 'ORDERS_DETAILS_STORE'
export const UPDATE_ORDER = 'UPDATE_ORDER'
