export const AUTH_KEY_IN_STORE = "auth";

export const SET_ACCESS_TOKEN = `${AUTH_KEY_IN_STORE}/SET_ACCESS_TOKEN`;
export const SET_REFRESH_TOKEN = `${AUTH_KEY_IN_STORE}/SET_REFRESH_TOKEN`;

export const CLEAR_KEYS = `${AUTH_KEY_IN_STORE}/CLEAR_KEYS`;
