export const AUTH_KEY_IN_STORE = "auth";

export const AUTH_LOGIN_REQUEST = `${AUTH_KEY_IN_STORE}/AUTH_LOGIN_REQUEST`;
export const AUTH_LOGIN_SUCCESS = `${AUTH_KEY_IN_STORE}/AUTH_LOGIN_SUCCESS`;
export const AUTH_LOGIN_FAILURE = `${AUTH_KEY_IN_STORE}/AUTH_LOGIN_FAILURE`;

export const AUTH_LOGOUT_REQUEST = `${AUTH_KEY_IN_STORE}/AUTH_LOGOUT_REQUEST`;
export const AUTH_CLEAR_SESSION = `${AUTH_KEY_IN_STORE}/AUTH_CLEAR_SESSION`;
export const AUTH_CLEAR_SESSION_FAILURE = `${AUTH_KEY_IN_STORE}/AUTH_CLEAR_SESSION_FAILURE`;

export const STORAGE_CURRENT_USER = "currentUser";
