export const AUTH_KEY_IN_STORE = 'auth';
export const AUTH_LOGIN_REQUEST = `${AUTH_KEY_IN_STORE}/AUTH_LOGIN_REQUEST`;
export const AUTH_LOGIN_SUCCESS = `${AUTH_KEY_IN_STORE}/AUTH_LOGIN_SUCCESS`;
export const AUTH_LOGIN_FAILURE = `${AUTH_KEY_IN_STORE}/AUTH_LOGIN_FAILURE`;

export const AUTH_LOGOUT_REQUEST = `${AUTH_KEY_IN_STORE}/AUTH_LOGOUT_REQUEST`;
export const AUTH_CLEAR_SESSION = `${AUTH_KEY_IN_STORE}/AUTH_CLEAR_SESSION`;
export const AUTH_CLEAR_SESSION_FAILURE = `${AUTH_KEY_IN_STORE}/AUTH_CLEAR_SESSION_FAILURE`;

export const SEND_OTP_REQUEST = `${AUTH_KEY_IN_STORE}/SEND_OTP_REQUEST`;
export const SEND_OTP_SUCCESS = `${AUTH_KEY_IN_STORE}/SEND_OTP_SUCCESS`;
export const SEND_OTP_FAILURE = `${AUTH_KEY_IN_STORE}/SEND_OTP_FAILURE`;

export const VALIDATE_OTP_REQUEST = `${AUTH_KEY_IN_STORE}/VALIDATE_OTP_REQUEST`;
export const VALIDATE_OTP_SUCCESS = `${AUTH_KEY_IN_STORE}/VALIDATE_OTP_SUCCESS`;
export const VALIDATE_OTP_FAILURE = `${AUTH_KEY_IN_STORE}/VALIDATE_OTP_FAILURE`;
export const CLEAR_OTP_CHALLENGE = `${AUTH_KEY_IN_STORE}/CLEAR_OTP_CHALLENGE`;

export const UPDATE_PASSWORD_REQUEST = `${AUTH_KEY_IN_STORE}/UPDATE_PASSWORD_REQUEST`;
export const UPDATE_PASSWORD_SUCCESS = `${AUTH_KEY_IN_STORE}/UPDATE_PASSWORD_SUCCESS`;
export const UPDATE_PASSWORD_FAILURE = `${AUTH_KEY_IN_STORE}/UPDATE_PASSWORD_FAILURE`;

export const START_ONBOARDING_PROCESS = `${AUTH_KEY_IN_STORE}/START_ONBOARDING_PROCESS`;
export const SET_DATA_USER = `${AUTH_KEY_IN_STORE}/SET_DATA_USER`;
export const RESET_SET_DATA_USER = `${AUTH_KEY_IN_STORE}/RESET_SET_DATA_USER`;
export const SET_DATA_SCHOOL = `${AUTH_KEY_IN_STORE}/SET_DATA_SCHOOL`;
export const RESET_SET_DATA_SCHOOL = `${AUTH_KEY_IN_STORE}/RESET_SET_DATA_SCHOOL`;
export const ONBOARDING_PROCESS_SUCCESS = `${AUTH_KEY_IN_STORE}/ONBOARDING_PROCESS_SUCCESS`;
export const SUBMIT_ONBOARDING_PROCESS = `${AUTH_KEY_IN_STORE}/SUBMIT_ONBOARDING_PROCESS`;

export const ONBOARDING_PROCESS_ERROR = `${AUTH_KEY_IN_STORE}/ONBOARDING_PROCESS_ERROR`;
export const CLEAR_ONBOARDING_PROCESS = `${AUTH_KEY_IN_STORE}/CLEAR_ONBOARDING_PROCESS`;

export const STORAGE_CURRENT_USER = 'currentUser';
